-- runs: one row per finished quiz round (PROJ-2, design.md → Data Model).
-- Rounds are immutable: nothing ever updates or deletes a row. They disappear
-- only with their profile, which is what makes account deletion (PROJ-4) able
-- to reach them (spec.md AC-26).

create table public.runs (
  id bigint generated always as identity primary key,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  streak smallint not null,
  duration_ms integer not null,
  -- Generated by the browser at round start. Unique, so a second submission of
  -- the same round cannot create a second row — the database is the guarantee,
  -- not a read-then-write check in application code (spec.md EC-4).
  client_round_id uuid not null unique,
  created_at timestamptz not null default now(),

  -- The plausibility bounds from AC-12, restated at the data layer so they
  -- survive a later refactor of the Server Action (rules/security.md: two
  -- independent checks). 500ms per answered question; streak is cast because
  -- 386 * 500 overflows smallint.
  constraint runs_streak_range check (streak >= 0 and streak <= 386),
  constraint runs_duration_non_negative check (duration_ms >= 0),
  constraint runs_duration_plausible check (duration_ms >= streak::integer * 500)
);

-- Serves three readers at once: the personal best (AC-8), the cascade when a
-- profile is deleted (AC-26), and PROJ-3's "best run per player". A separate
-- index on profile_id would be redundant — it is the leftmost column here.
create index runs_profile_best_idx
  on public.runs (profile_id, streak desc, duration_ms asc);

alter table public.runs enable row level security;

-- Read only your own runs. docs/data-model.md promises "bad rounds are private";
-- a select policy open to every authenticated user would hand the full history
-- of every player to anyone holding the public anon key. PROJ-3's leaderboard
-- does not read this table directly — it gets a function returning only the
-- best run per player.
-- auth.uid() is wrapped in a subquery so it is evaluated once per statement
-- instead of once per row (supabase-postgres-best-practices → security-rls-performance).
create policy "runs_select_own"
  on public.runs for select
  to authenticated
  using ((select auth.uid()) = profile_id);

-- Insert only for yourself: a forged profile_id is rejected by the database,
-- not just by the Server Action (spec.md AC-14).
create policy "runs_insert_own"
  on public.runs for insert
  to authenticated
  with check ((select auth.uid()) = profile_id);

-- No update or delete policies on purpose: a finished round is immutable
-- (docs/data-model.md → "Nothing is ever overwritten").
